AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'app/controllers/users/confirmations_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'lib/extensions/simple_form/inputs/array_input.rb'
    - 'vendor/assets/**/**/*'
    - 'spec/factories/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/SymbolArray:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
